import approachPlants from "../assets/approach-plants.jpg";
import type { LocalizedText, LocalizedList } from "./therapies";

export type Plant = {
  slug: string;
  commonName: LocalizedText;
  latinName: string;
  image: string;
  properties: LocalizedList;
  uses: LocalizedText;
};

export const PLANTS: Plant[] = [
  {
    slug: "lavande",
    latinName: "Lavandula angustifolia",
    image: approachPlants,
    commonName: { fr: "Lavande", en: "Lavender", es: "Lavanda", de: "Lavendel", it: "Lavanda", nl: "Lavendel", pl: "Lawenda", pt: "Lavanda" },
    properties: {
      fr: ["Calmante", "Antispasmodique", "Cicatrisante"],
      en: ["Calming", "Antispasmodic", "Healing"],
      es: ["Calmante", "Antiespasmódica", "Cicatrizante"],
      de: ["Beruhigend", "Krampflösend", "Heilend"],
      it: ["Calmante", "Antispasmodica", "Cicatrizzante"],
      nl: ["Kalmerend", "Krampstillend", "Helend"],
      pl: ["Kojąca", "Rozkurczowa", "Gojąca"],
      pt: ["Calmante", "Antiespasmódica", "Cicatrizante"],
    },
    uses: {
      fr: "Anxiété, insomnie, irritations cutanées.",
      en: "Anxiety, insomnia, skin irritations.",
      es: "Ansiedad, insomnio, irritaciones cutáneas.",
      de: "Angst, Schlaflosigkeit, Hautreizungen.",
      it: "Ansia, insonnia, irritazioni cutanee.",
      nl: "Angst, slapeloosheid, huidirritaties.",
      pl: "Lęk, bezsenność, podrażnienia skóry.",
      pt: "Ansiedade, insónia, irritações cutâneas.",
    },
  },
  {
    slug: "camomille",
    latinName: "Matricaria chamomilla",
    image: approachPlants,
    commonName: { fr: "Camomille", en: "Chamomile", es: "Manzanilla", de: "Kamille", it: "Camomilla", nl: "Kamille", pl: "Rumianek", pt: "Camomila" },
    properties: {
      fr: ["Apaisante", "Digestive", "Anti-inflammatoire"],
      en: ["Soothing", "Digestive", "Anti-inflammatory"],
      es: ["Calmante", "Digestiva", "Antiinflamatoria"],
      de: ["Beruhigend", "Verdauungsfördernd", "Entzündungshemmend"],
      it: ["Lenitiva", "Digestiva", "Antinfiammatoria"],
      nl: ["Verzachtend", "Spijsverteringsbevorderend", "Ontstekingsremmend"],
      pl: ["Łagodząca", "Trawienna", "Przeciwzapalna"],
      pt: ["Calmante", "Digestiva", "Anti-inflamatória"],
    },
    uses: {
      fr: "Digestion difficile, sommeil, irritations.",
      en: "Difficult digestion, sleep, irritations.",
      es: "Digestión difícil, sueño, irritaciones.",
      de: "Verdauungsbeschwerden, Schlaf, Reizungen.",
      it: "Digestione difficile, sonno, irritazioni.",
      nl: "Moeilijke spijsvertering, slaap, irritaties.",
      pl: "Trudne trawienie, sen, podrażnienia.",
      pt: "Digestão difícil, sono, irritações.",
    },
  },
  {
    slug: "millepertuis",
    latinName: "Hypericum perforatum",
    image: approachPlants,
    commonName: { fr: "Millepertuis", en: "St. John's Wort", es: "Hipérico", de: "Johanniskraut", it: "Iperico", nl: "Sint-janskruid", pl: "Dziurawiec", pt: "Hipericão" },
    properties: {
      fr: ["Antidépresseur naturel", "Cicatrisante", "Antivirale"],
      en: ["Natural antidepressant", "Healing", "Antiviral"],
      es: ["Antidepresivo natural", "Cicatrizante", "Antiviral"],
      de: ["Natürliches Antidepressivum", "Heilend", "Antiviral"],
      it: ["Antidepressivo naturale", "Cicatrizzante", "Antivirale"],
      nl: ["Natuurlijk antidepressivum", "Helend", "Antiviraal"],
      pl: ["Naturalny przeciwdepresyjny", "Gojący", "Przeciwwirusowy"],
      pt: ["Antidepressivo natural", "Cicatrizante", "Antiviral"],
    },
    uses: {
      fr: "Déprime saisonnière, blessures, brûlures légères.",
      en: "Seasonal blues, wounds, mild burns.",
      es: "Tristeza estacional, heridas, quemaduras leves.",
      de: "Saisonale Verstimmungen, Wunden, leichte Verbrennungen.",
      it: "Malinconia stagionale, ferite, ustioni lievi.",
      nl: "Seizoensblues, wonden, lichte brandwonden.",
      pl: "Sezonowy spadek nastroju, rany, lekkie oparzenia.",
      pt: "Tristeza sazonal, feridas, queimaduras leves.",
    },
  },
  {
    slug: "melisse",
    latinName: "Melissa officinalis",
    image: approachPlants,
    commonName: { fr: "Mélisse", en: "Lemon balm", es: "Melisa", de: "Melisse", it: "Melissa", nl: "Citroenmelisse", pl: "Melisa", pt: "Erva-cidreira" },
    properties: {
      fr: ["Calmante", "Antispasmodique", "Antivirale"],
      en: ["Calming", "Antispasmodic", "Antiviral"],
      es: ["Calmante", "Antiespasmódica", "Antiviral"],
      de: ["Beruhigend", "Krampflösend", "Antiviral"],
      it: ["Calmante", "Antispasmodica", "Antivirale"],
      nl: ["Kalmerend", "Krampstillend", "Antiviraal"],
      pl: ["Kojąca", "Rozkurczowa", "Przeciwwirusowa"],
      pt: ["Calmante", "Antiespasmódica", "Antiviral"],
    },
    uses: {
      fr: "Stress, troubles digestifs nerveux, sommeil agité.",
      en: "Stress, nervous digestive troubles, restless sleep.",
      es: "Estrés, trastornos digestivos nerviosos, sueño inquieto.",
      de: "Stress, nervöse Verdauungsbeschwerden, unruhiger Schlaf.",
      it: "Stress, disturbi digestivi nervosi, sonno agitato.",
      nl: "Stress, nerveuze spijsverteringsklachten, onrustige slaap.",
      pl: "Stres, nerwowe dolegliwości trawienne, niespokojny sen.",
      pt: "Stress, distúrbios digestivos nervosos, sono agitado.",
    },
  },
  {
    slug: "sauge",
    latinName: "Salvia officinalis",
    image: approachPlants,
    commonName: { fr: "Sauge", en: "Sage", es: "Salvia", de: "Salbei", it: "Salvia", nl: "Salie", pl: "Szałwia", pt: "Salva" },
    properties: {
      fr: ["Purifiante", "Hormonale", "Antiseptique"],
      en: ["Purifying", "Hormonal", "Antiseptic"],
      es: ["Purificante", "Hormonal", "Antiséptica"],
      de: ["Reinigend", "Hormonell", "Antiseptisch"],
      it: ["Purificante", "Ormonale", "Antisettica"],
      nl: ["Zuiverend", "Hormonaal", "Antiseptisch"],
      pl: ["Oczyszczająca", "Hormonalna", "Antyseptyczna"],
      pt: ["Purificante", "Hormonal", "Antisséptica"],
    },
    uses: {
      fr: "Bouffées de chaleur, maux de gorge, purification d'espace.",
      en: "Hot flashes, sore throats, space purification.",
      es: "Sofocos, dolor de garganta, purificación del espacio.",
      de: "Hitzewallungen, Halsschmerzen, Raumreinigung.",
      it: "Vampate, mal di gola, purificazione degli spazi.",
      nl: "Opvliegers, keelpijn, ruimtezuivering.",
      pl: "Uderzenia gorąca, bóle gardła, oczyszczanie przestrzeni.",
      pt: "Afrontamentos, dor de garganta, purificação do espaço.",
    },
  },
  {
    slug: "thym",
    latinName: "Thymus vulgaris",
    image: approachPlants,
    commonName: { fr: "Thym", en: "Thyme", es: "Tomillo", de: "Thymian", it: "Timo", nl: "Tijm", pl: "Tymianek", pt: "Tomilho" },
    properties: {
      fr: ["Antiseptique", "Expectorant", "Immunostimulant"],
      en: ["Antiseptic", "Expectorant", "Immune booster"],
      es: ["Antiséptico", "Expectorante", "Inmunoestimulante"],
      de: ["Antiseptisch", "Schleimlösend", "Immunstärkend"],
      it: ["Antisettico", "Espettorante", "Immunostimolante"],
      nl: ["Antiseptisch", "Slijmoplossend", "Immuunversterkend"],
      pl: ["Antyseptyczny", "Wykrztuśny", "Wzmacniający odporność"],
      pt: ["Antisséptico", "Expectorante", "Imunoestimulante"],
    },
    uses: {
      fr: "Affections respiratoires, fatigue, défenses naturelles.",
      en: "Respiratory issues, fatigue, natural defenses.",
      es: "Afecciones respiratorias, fatiga, defensas naturales.",
      de: "Atemwegsbeschwerden, Müdigkeit, Abwehrkräfte.",
      it: "Affezioni respiratorie, stanchezza, difese naturali.",
      nl: "Luchtwegklachten, vermoeidheid, natuurlijke afweer.",
      pl: "Dolegliwości oddechowe, zmęczenie, naturalna odporność.",
      pt: "Afeções respiratórias, cansaço, defesas naturais.",
    },
  },
  {
    slug: "achillee",
    latinName: "Achillea millefolium",
    image: approachPlants,
    commonName: { fr: "Achillée millefeuille", en: "Yarrow", es: "Milenrama", de: "Schafgarbe", it: "Achillea", nl: "Duizendblad", pl: "Krwawnik", pt: "Mil-folhas" },
    properties: {
      fr: ["Hémostatique", "Régulatrice du cycle", "Tonique"],
      en: ["Hemostatic", "Cycle regulator", "Tonic"],
      es: ["Hemostática", "Reguladora del ciclo", "Tónica"],
      de: ["Blutstillend", "Zyklusregulierend", "Stärkend"],
      it: ["Emostatica", "Regolatrice del ciclo", "Tonica"],
      nl: ["Bloedstelpend", "Cyclusregulerend", "Versterkend"],
      pl: ["Krwiotamująca", "Regulująca cykl", "Wzmacniająca"],
      pt: ["Hemostática", "Reguladora do ciclo", "Tónica"],
    },
    uses: {
      fr: "Cycles féminins, petites coupures, digestion.",
      en: "Female cycles, small cuts, digestion.",
      es: "Ciclos femeninos, pequeños cortes, digestión.",
      de: "Frauenzyklus, kleine Schnitte, Verdauung.",
      it: "Cicli femminili, piccoli tagli, digestione.",
      nl: "Vrouwelijke cyclus, kleine sneetjes, spijsvertering.",
      pl: "Cykle kobiece, drobne skaleczenia, trawienie.",
      pt: "Ciclos femininos, pequenos cortes, digestão.",
    },
  },
  {
    slug: "passiflore",
    latinName: "Passiflora incarnata",
    image: approachPlants,
    commonName: { fr: "Passiflore", en: "Passionflower", es: "Pasiflora", de: "Passionsblume", it: "Passiflora", nl: "Passiebloem", pl: "Męczennica", pt: "Maracujá" },
    properties: {
      fr: ["Sédative douce", "Anxiolytique", "Antispasmodique"],
      en: ["Gentle sedative", "Anxiolytic", "Antispasmodic"],
      es: ["Sedante suave", "Ansiolítica", "Antiespasmódica"],
      de: ["Sanft beruhigend", "Angstlösend", "Krampflösend"],
      it: ["Sedativa dolce", "Ansiolitica", "Antispasmodica"],
      nl: ["Zacht kalmerend", "Angstwerend", "Krampstillend"],
      pl: ["Łagodnie uspokajająca", "Przeciwlękowa", "Rozkurczowa"],
      pt: ["Sedativa suave", "Ansiolítica", "Antiespasmódica"],
    },
    uses: {
      fr: "Anxiété, troubles du sommeil, nervosité.",
      en: "Anxiety, sleep troubles, nervousness.",
      es: "Ansiedad, trastornos del sueño, nerviosismo.",
      de: "Angst, Schlafstörungen, Nervosität.",
      it: "Ansia, disturbi del sonno, nervosismo.",
      nl: "Angst, slaapproblemen, nervositeit.",
      pl: "Lęk, problemy ze snem, nerwowość.",
      pt: "Ansiedade, distúrbios do sono, nervosismo.",
    },
  },
];
