/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemoignagesRouteImport } from './routes/temoignages'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PolitiqueDeConfidentialiteRouteImport } from './routes/politique-de-confidentialite'
import { Route as PlantesEtRemedesRouteImport } from './routes/plantes-et-remedes'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SoinsEtTherapiesIndexRouteImport } from './routes/soins-et-therapies.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SoinsEtTherapiesSlugRouteImport } from './routes/soins-et-therapies.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as AdminPostsIdRouteImport } from './routes/admin.posts.$id'

const TemoignagesRoute = TemoignagesRouteImport.update({
  id: '/temoignages',
  path: '/temoignages',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueDeConfidentialiteRoute =
  PolitiqueDeConfidentialiteRouteImport.update({
    id: '/politique-de-confidentialite',
    path: '/politique-de-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlantesEtRemedesRoute = PlantesEtRemedesRouteImport.update({
  id: '/plantes-et-remedes',
  path: '/plantes-et-remedes',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoinsEtTherapiesIndexRoute = SoinsEtTherapiesIndexRouteImport.update({
  id: '/soins-et-therapies/',
  path: '/soins-et-therapies/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoinsEtTherapiesSlugRoute = SoinsEtTherapiesSlugRouteImport.update({
  id: '/soins-et-therapies/$slug',
  path: '/soins-et-therapies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsIdRoute = AdminPostsIdRouteImport.update({
  id: '/admin/posts/$id',
  path: '/admin/posts/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/plantes-et-remedes': typeof PlantesEtRemedesRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/temoignages': typeof TemoignagesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/soins-et-therapies/$slug': typeof SoinsEtTherapiesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/soins-et-therapies/': typeof SoinsEtTherapiesIndexRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/api/public/contact': typeof ApiPublicContactRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/plantes-et-remedes': typeof PlantesEtRemedesRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/temoignages': typeof TemoignagesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/soins-et-therapies/$slug': typeof SoinsEtTherapiesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/soins-et-therapies': typeof SoinsEtTherapiesIndexRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/api/public/contact': typeof ApiPublicContactRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/plantes-et-remedes': typeof PlantesEtRemedesRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/temoignages': typeof TemoignagesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/soins-et-therapies/$slug': typeof SoinsEtTherapiesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/soins-et-therapies/': typeof SoinsEtTherapiesIndexRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/api/public/contact': typeof ApiPublicContactRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/mentions-legales'
    | '/plantes-et-remedes'
    | '/politique-de-confidentialite'
    | '/sitemap.xml'
    | '/temoignages'
    | '/blog/$slug'
    | '/soins-et-therapies/$slug'
    | '/admin/'
    | '/soins-et-therapies/'
    | '/admin/posts/$id'
    | '/api/public/contact'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/mentions-legales'
    | '/plantes-et-remedes'
    | '/politique-de-confidentialite'
    | '/sitemap.xml'
    | '/temoignages'
    | '/blog/$slug'
    | '/soins-et-therapies/$slug'
    | '/admin'
    | '/soins-et-therapies'
    | '/admin/posts/$id'
    | '/api/public/contact'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/mentions-legales'
    | '/plantes-et-remedes'
    | '/politique-de-confidentialite'
    | '/sitemap.xml'
    | '/temoignages'
    | '/blog/$slug'
    | '/soins-et-therapies/$slug'
    | '/admin/'
    | '/soins-et-therapies/'
    | '/admin/posts/$id'
    | '/api/public/contact'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PlantesEtRemedesRoute: typeof PlantesEtRemedesRoute
  PolitiqueDeConfidentialiteRoute: typeof PolitiqueDeConfidentialiteRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TemoignagesRoute: typeof TemoignagesRoute
  SoinsEtTherapiesSlugRoute: typeof SoinsEtTherapiesSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  SoinsEtTherapiesIndexRoute: typeof SoinsEtTherapiesIndexRoute
  AdminPostsIdRoute: typeof AdminPostsIdRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/temoignages': {
      id: '/temoignages'
      path: '/temoignages'
      fullPath: '/temoignages'
      preLoaderRoute: typeof TemoignagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-de-confidentialite': {
      id: '/politique-de-confidentialite'
      path: '/politique-de-confidentialite'
      fullPath: '/politique-de-confidentialite'
      preLoaderRoute: typeof PolitiqueDeConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plantes-et-remedes': {
      id: '/plantes-et-remedes'
      path: '/plantes-et-remedes'
      fullPath: '/plantes-et-remedes'
      preLoaderRoute: typeof PlantesEtRemedesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soins-et-therapies/': {
      id: '/soins-et-therapies/'
      path: '/soins-et-therapies'
      fullPath: '/soins-et-therapies/'
      preLoaderRoute: typeof SoinsEtTherapiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soins-et-therapies/$slug': {
      id: '/soins-et-therapies/$slug'
      path: '/soins-et-therapies/$slug'
      fullPath: '/soins-et-therapies/$slug'
      preLoaderRoute: typeof SoinsEtTherapiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts/$id': {
      id: '/admin/posts/$id'
      path: '/admin/posts/$id'
      fullPath: '/admin/posts/$id'
      preLoaderRoute: typeof AdminPostsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PlantesEtRemedesRoute: PlantesEtRemedesRoute,
  PolitiqueDeConfidentialiteRoute: PolitiqueDeConfidentialiteRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TemoignagesRoute: TemoignagesRoute,
  SoinsEtTherapiesSlugRoute: SoinsEtTherapiesSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  SoinsEtTherapiesIndexRoute: SoinsEtTherapiesIndexRoute,
  AdminPostsIdRoute: AdminPostsIdRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
